algoritmo "Área da circunferência"
//Faça um algoritmo para calcular a área de uma
//circunferência, considerando a fórmula ÁREA = p * RAIO^2.
//Utilize as variáveis AREA e RAIO, a constante p
//(pi =3,14159) e os operadores aritméticos de multiplicação
var
   AREA,RAIO:REAL
inicio

      escreva("Raio: ")
      leia(RAIO)
      AREA<-PI * RAIO^2
      escreva("Área da circuferência: ",AREA)
fimalgoritmo